POST http://localhost:3000/send-post HTTP/1.1
content-type: application/json

{"CompanyName": "Superpeer", "CompanyWebsite": "superpeer.com", "CompanyEmail": "superpeer@gmail.com", "JobTitle": "Frontend Developer", "JobCategory": "Remote", "JobLevel": "Jr.", "JobDescription": "Test"}

###
